name: Deploy to github pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config --global user.email "www.felix4real98@gmail.com"
          git config --global user.name "felix-phil"
          git remote set-url origin https://felix-phil:${{secrets.GITHUB_TOKEN}}@github.com/felix-phil/portfolio.git
          yarn install && yarn run deploy